name: laravel-deployment
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, curl, zip, etc.

      - name: Install Composer Dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev

      - name: Create .env file
        run: |
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          # Add other environment variables as needed

      - name: Create Zip deployment package
        run: zip -r deploy.zip ./

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: Meerab
          environment_name: Meerab-env
          existing_bucket_name: elasticbeanstalk-us-east-1-975049940648
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
